/* GUI package */
package pdb18.gui;

/* IMPORTS */
import pdb18.connection.OracleDBConnection;

import pdb18.gui.components.MainPanel;
import pdb18.gui.components.LoginPanel;


/**
 * A class that extends thread that is to be called when program is exiting
 * 
 * @author Tomas Aubrecht (xaubre02@stud.fit.vutbr.cz)
 */
class ExitOfAppGUI extends Thread {

    @Override
    public void run() {
        OracleDBConnection.disconnect();
   }
}

/**
 * Application GUI main class. Contains main method.
 * 
 * @author Tomas Aubrecht (xaubre02@stud.fit.vutbr.cz)
 */
public final class AppGUI extends javax.swing.JFrame {

    /**
     * Create a new application GUI.
     */
    public AppGUI() {
        initComponents();
        setContentPane(new LoginPanel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("pdb18");
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(1022, 783));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1022, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Switch between Login panel and Main application panel.
     * 
     * @param flag logged status flag
     */
    public void setLogged(boolean flag) {
        if (flag) {
            setContentPane(new MainPanel());
            validate();
        } else {
            setContentPane(new LoginPanel());
            validate();
        }
    }
    
    /**
     * Main application method.
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Initialize the Oracle Connection settings */
        OracleDBConnection.init(args);
        
        /* Add cleanup operations */
        Runtime.getRuntime().addShutdownHook(new ExitOfAppGUI());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
