/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pdb18.gui.databases;

import java.awt.Point;
import javax.swing.JOptionPane;

import java.util.Vector;

/**
 * Graphic panel with map of ZOO.
 * Allows user to display, modify and work with ZOO map.
 *
 * @author David Bednařík (xbedna62@stud.fit.vutbr.cz)
 */
public class MapPanel extends javax.swing.JPanel {

	/**
	 * Creates new form MapPanel
	 */
	public MapPanel() {
		initComponents();

		zooMap.setButtonAddEnclosure(addEnclosure);
		zooMap.setButtonAddPark(addPark);
		zooMap.setButtonAddLake(addLake);
		zooMap.setButtonAddTree(addTree);
		zooMap.setButtonAddPath(addPath);
		zooMap.setButtonSave(save);
		zooMap.setButtonDistance(buttonDistance);
		zooMap.setButtonInside(buttonInside);
		zooMap.setButtonNeighbors(buttonNeighbors);
		zooMap.setButtonRelate(buttonRelate);
                zooMap.setButtonMostFood(buttonMostFood);
		zooMap.setLabelArea(labelAreaIn);
		zooMap.setLabelLength(labelLengthIn);
		zooMap.setTextFieldEnclosureType(textFieldEnclosureType);
		zooMap.setListOfAnimals(listOfAnimals);
		zooMap.setDatePickerValidFrom(dateValidFrom);
		zooMap.setDatePickerValidTo(dateValidTo);
		zooMap.initilizeButtonListeners();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        labelAddMapObject = new javax.swing.JLabel();
        addEnclosure = new javax.swing.JButton();
        addPark = new javax.swing.JButton();
        addLake = new javax.swing.JButton();
        addTree = new javax.swing.JButton();
        addPath = new javax.swing.JButton();
        zooMap = new pdb18.gui.spatial.ZooMap();
        jPanel1 = new javax.swing.JPanel();
        buttonDistance = new javax.swing.JButton();
        buttonRelate = new javax.swing.JButton();
        buttonInside = new javax.swing.JButton();
        buttonNeighbors = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelArea = new javax.swing.JLabel();
        labelLength = new javax.swing.JLabel();
        labelAreaIn = new javax.swing.JLabel();
        labelLengthIn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelEnclosureType = new javax.swing.JLabel();
        labelAnimals = new javax.swing.JLabel();
        textFieldEnclosureType = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listOfAnimals = new javax.swing.JList<>();
        buttonMostFood = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        reload = new javax.swing.JButton();
        save = new javax.swing.JButton();
        dateValidFrom = new org.jdesktop.swingx.JXDatePicker();
        dateValidTo = new org.jdesktop.swingx.JXDatePicker();
        labelMapValidityFrom = new javax.swing.JLabel();
        labelMapValidityTo = new javax.swing.JLabel();

        labelAddMapObject.setText("Přidej:");

        addEnclosure.setText("Výběh");
        addEnclosure.setRolloverEnabled(false);

        addPark.setText("Park");
        addPark.setRolloverEnabled(false);

        addLake.setText("Vodní plocha");
        addLake.setRolloverEnabled(false);

        addTree.setText("Strom");
        addTree.setRolloverEnabled(false);

        addPath.setText("Cestu");
        addPath.setRolloverEnabled(false);

        zooMap.setBackground(new java.awt.Color(255, 255, 255));
        zooMap.setMaximumSize(new java.awt.Dimension(650, 650));
        zooMap.setMinimumSize(new java.awt.Dimension(650, 650));
        zooMap.setNextFocusableComponent(save);

        javax.swing.GroupLayout zooMapLayout = new javax.swing.GroupLayout(zooMap);
        zooMap.setLayout(zooMapLayout);
        zooMapLayout.setHorizontalGroup(
            zooMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        zooMapLayout.setVerticalGroup(
            zooMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Akce"));

        buttonDistance.setText("Zjísti vzdálenost dvou objektů");

        buttonRelate.setText("Zjísti vztah dvou objektů");

        buttonInside.setText("Zvýrazni všechny objektu uvnitř označeného objektu");

        buttonNeighbors.setText("Zvýrazni sousedy označeného objektu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonDistance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonRelate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(buttonInside, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
            .addComponent(buttonNeighbors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buttonDistance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRelate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonInside)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonNeighbors))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail označneného objektu"));

        labelArea.setText("Plocha:");
        labelArea.setToolTipText("");

        labelLength.setText("Délka/Obvod:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLength)
                    .addComponent(labelArea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAreaIn)
                    .addComponent(labelLengthIn))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelArea)
                    .addComponent(labelAreaIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLength)
                    .addComponent(labelLengthIn)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail označeného výběhu"));

        labelEnclosureType.setText("Typ: ");

        labelAnimals.setText("Zvířata:");

        jScrollPane1.setViewportView(listOfAnimals);

        buttonMostFood.setText("Vyber zvíře, které potřebuje nejvíce krmení");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAnimals)
                    .addComponent(labelEnclosureType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldEnclosureType)
                    .addComponent(jScrollPane1)))
            .addComponent(buttonMostFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEnclosureType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnclosureType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelAnimals)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonMostFood)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Změny"));

        reload.setText("Načti mapu pro zvolený interval");
        reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadActionPerformed(evt);
            }
        });

        save.setText("Uložit změny");

        labelMapValidityFrom.setText("Datum validity od:");

        labelMapValidityTo.setText("Datum validity do:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMapValidityFrom)
                    .addComponent(labelMapValidityTo))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateValidFrom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateValidTo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(reload, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateValidFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMapValidityFrom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMapValidityTo)
                    .addComponent(dateValidTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reload)
                .addGap(18, 18, 18)
                .addComponent(save))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zooMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(labelAddMapObject, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addEnclosure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPark)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addLake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addTree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addPath)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelAddMapObject)
                            .addComponent(addEnclosure)
                            .addComponent(addPark)
                            .addComponent(addLake)
                            .addComponent(addTree)
                            .addComponent(addPath))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zooMap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadActionPerformed
        zooMap.loadFromDatabase();
    }//GEN-LAST:event_reloadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnclosure;
    private javax.swing.JButton addLake;
    private javax.swing.JButton addPark;
    private javax.swing.JButton addPath;
    private javax.swing.JButton addTree;
    private javax.swing.JButton buttonDistance;
    private javax.swing.JButton buttonInside;
    private javax.swing.JButton buttonMostFood;
    private javax.swing.JButton buttonNeighbors;
    private javax.swing.JButton buttonRelate;
    private org.jdesktop.swingx.JXDatePicker dateValidFrom;
    private org.jdesktop.swingx.JXDatePicker dateValidTo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddMapObject;
    private javax.swing.JLabel labelAnimals;
    private javax.swing.JLabel labelArea;
    private javax.swing.JLabel labelAreaIn;
    private javax.swing.JLabel labelEnclosureType;
    private javax.swing.JLabel labelLength;
    private javax.swing.JLabel labelLengthIn;
    private javax.swing.JLabel labelMapValidityFrom;
    private javax.swing.JLabel labelMapValidityTo;
    private javax.swing.JList<String> listOfAnimals;
    private javax.swing.JPanel panel1;
    private javax.swing.JButton reload;
    private javax.swing.JButton save;
    private javax.swing.JTextField textFieldEnclosureType;
    private pdb18.gui.spatial.ZooMap zooMap;
    // End of variables declaration//GEN-END:variables
}
