/* Components package */
package pdb18.gui.components;

/* IMPORTS */
import java.awt.Color;
import pdb18.gui.AppGUI;
import pdb18.connection.OracleDBConnection;

/**
 * Login panel of the application.
 * 
 * @author Tomas Aubrecht (xaubre02@stud.fit.vutbr.cz)
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Create a new LoginPanel.
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enclosingPanel = new javax.swing.JPanel();
        passLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 250, 250));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, new java.awt.Color(29, 161, 242)));
        setMinimumSize(new java.awt.Dimension(300, 200));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        enclosingPanel.setBackground(new java.awt.Color(255, 255, 255));
        enclosingPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(29, 161, 242), 1, true));
        enclosingPanel.setMinimumSize(new java.awt.Dimension(300, 200));
        enclosingPanel.setPreferredSize(new java.awt.Dimension(300, 200));

        passLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        passLabel.setForeground(new java.awt.Color(68, 68, 68));
        passLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLabel.setText("Heslo");

        userLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        userLabel.setForeground(new java.awt.Color(68, 68, 68));
        userLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        userLabel.setText("Uživatel");

        userField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        userField.setForeground(new java.awt.Color(68, 68, 68));

        passField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        passField.setForeground(new java.awt.Color(68, 68, 68));
        passField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passFieldKeyReleased(evt);
            }
        });

        loginButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(68, 68, 68));
        loginButton.setText("Přihlásit");
        loginButton.setFocusPainted(false);
        loginButton.setFocusable(false);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                loginButtonKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout enclosingPanelLayout = new javax.swing.GroupLayout(enclosingPanel);
        enclosingPanel.setLayout(enclosingPanelLayout);
        enclosingPanelLayout.setHorizontalGroup(
            enclosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enclosingPanelLayout.createSequentialGroup()
                .addGroup(enclosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enclosingPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(loginButton))
                    .addGroup(enclosingPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(enclosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userLabel)
                            .addComponent(passLabel))
                        .addGap(18, 18, 18)
                        .addGroup(enclosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        enclosingPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passLabel, userLabel});

        enclosingPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passField, userField});

        enclosingPanelLayout.setVerticalGroup(
            enclosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enclosingPanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(enclosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLabel))
                .addGap(18, 18, 18)
                .addGroup(enclosingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passLabel)
                    .addComponent(passField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addGap(25, 25, 25))
        );

        enclosingPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passLabel, userLabel});

        enclosingPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passField, userField});

        add(enclosingPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginButtonKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            processLogin();
        }
    }//GEN-LAST:event_loginButtonKeyReleased

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        processLogin();
    }//GEN-LAST:event_loginButtonActionPerformed

    private void passFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passFieldKeyReleased
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            processLogin();
        }
    }//GEN-LAST:event_passFieldKeyReleased

    /**
     * Login to the database and grant access to the whole application.
     */
    private void processLogin() {
        userField.setEditable(false);
        passField.setEditable(false);

        String user = userField.getText();
        String pass = new String(passField.getPassword());
        if (OracleDBConnection.connect(user, pass)) {
            /* Get the main frame */
            AppGUI app = (AppGUI)javax.swing.SwingUtilities.getWindowAncestor(this);
            app.setLogged(true);
        } else {
            /* Change input fields color */
            Color color = new Color(255, 200, 200);
            userField.setBackground(color);
            passField.setBackground(color);
            /* Show dialog message */
            javax.swing.JOptionPane.showMessageDialog(null, "Invalid username/password.", "Login error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

        userField.setEditable(true);
        passField.setEditable(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel enclosingPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField userField;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
